# Generated by Django 2.1.2 on 2018-11-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosOrganizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('rif', models.CharField(max_length=30)),
                ('dir_oficina', models.CharField(max_length=130)),
                ('representante_legal', models.CharField(max_length=130)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DatosProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=130)),
                ('ubicacion', models.CharField(max_length=130)),
                ('area', models.CharField(max_length=130)),
                ('tipo', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='DatosSolicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cedula', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
