from django.contrib import admin
from .models import *

admin.site.register(DatosProyecto)
admin.site.register(DatosSolicitante)
admin.site.register(DatosOrganizacion)
admin.site.register(DatosEspacio)
admin.site.register(DatosPersonal)
admin.site.register(DatosDocumento)
admin.site.register(DescripcionProyecto)
admin.site.register(Suelo)
admin.site.register(Agua)
admin.site.register(Aire)
admin.site.register(ConclusionFisico)
admin.site.register(Forestal)
admin.site.register(Flora)
admin.site.register(Fauna)
admin.site.register(ConclusionBiologico)
admin.site.register(Social)
admin.site.register(Economica)
admin.site.register(Cultural)
admin.site.register(ConclusionCultural)
admin.site.register(Actividades)
admin.site.register(Comentarios)
admin.site.register(Diagrama)
admin.site.register(TalentoHumano)
admin.site.register(Servicios)
admin.site.register(Pasajes)
admin.site.register(RecursosMateriales)
admin.site.register(Oficina)
admin.site.register(Insumos)
admin.site.register(PlanInversion)
admin.site.register(Informacion)
admin.site.register(Responsable)

